# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

mrr <- function(Y, X, cores = 2L, maxit = 1000L) {
    .Call('_SoyNAM_mrr', PACKAGE = 'SoyNAM', Y, X, cores, maxit)
}

